spring.application.name=HGS
# 1. PostgreSQL Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/hibrit_giris_db
spring.datasource.username=postgres
spring.datasource.password=12345

# 2. Hibernate ve JPA Ayarları (Veritabanı Yönetimi)
# 'update' komutu, Java'da oluşturduğumuz sınıflara bakarak tabloları otomatik günceller
spring.jpa.hibernate.ddl-auto=update

# Arka planda çalışan SQL sorgularını konsolda görmek için (Hata ayıklamayı kolaylaştırır)
spring.jpa.show-sql=true

# PostgreSQL'in diline uygun SQL sorguları üretmesi için Dialect ayarı
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Agdaki diger cihazlardan (ESP32, telefon) erisim icin tum arayuzlere dinleme
server.address=0.0.0.0
server.port=8080